[gspread]
type = "service_account"
project_id = "your-gcp-project-id" # Ganti dengan ID Proyek Anda

private_key_id = "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0" # Ganti dengan ID Kunci Anda

# Bagian private_key ini SANGAT PENTING. Gunakan triple quotes dan masukkan seluruh key termasuk header dan footer.
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBAA...
... (Seluruh isi dari kunci rahasia Anda, biasanya berupa string panjang) ...
-----END PRIVATE KEY-----
"""

client_email = "nama-akun-layanan@your-gcp-project-id.iam.gserviceaccount.com" # Ganti dengan Email Klien Anda

client_id = "123456789012345678901"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/..."
